name: Update Weather Data

on:
  schedule:
    - cron: "0 * * * *"  # Runs at the start of every hour (UTC time)
  workflow_dispatch: # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      # Step 4: Run the Python script to fetch weather data
      - name: Fetch Weather Data
        run: |
          python fetch_weather.py

      # Step 5: Commit and push changes to the repository
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_weather.csv
          git commit -m "Update weather data"
          git push
